-- 테이블 삭제
DROP TABLE ALERT;
DROP TABLE TABLE_NAME;
DROP TABLE MEMBER;

-- 시퀀스 삭제
DROP SEQUENCE SEQ_MEM_NO;


-- 시퀀스 생성
CREATE SEQUENCE SEQ_MEM_NO
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;
    
-- 자유게시판 시퀀스 생성
CREATE SEQUENCE SEQ_BOARD
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

-- 공지사항 시퀀스 생성
CREATE SEQUENCE SEQ_NTC
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;


-- 테이블 구분 테이블
CREATE TABLE TABLE_NAME(
    TABLE_NO NUMBER PRIMARY KEY,
    TABLE_NAME VARCHAR2(100) NOT NULL
);

-- 멤버테이블 생성
CREATE TABLE MEMBER(
    MEM_NO NUMBER PRIMARY KEY,
    MEM_TOKEN VARCHAR2(1000),
    MEM_ID VARCHAR2(100) NOT NULL UNIQUE,
    MEM_BIRTH DATE NOT NULL,
    MEM_PHONE VARCHAR2(100) NOT NULL,
    MEM_NAME VARCHAR2(50) NOT NULL,
    MEM_STATUS_NY CHAR(10) DEFAULT 'Y' CONSTRAINT MEM_STATUS_NY_CK CHECK(MEM_STATUS_NY IN('Y','N')),
    MEM_NICKNAME VARCHAR2(50),
    MEM_INTRODUCE VARCHAR2(3000),
    MEM_RPR_CUM NUMBER,
    MEM_IMG VARCHAR2(1000),
    MEM_ADMIN_NY CHAR(10) DEFAULT 'N' CONSTRAINT MEM_ADMIN_NY_CK CHECK(MEM_ADMIN_NY IN('Y','N'))
    );

-- 알림 테이블 생성
CREATE TABLE ALERT(
    ID_NO NUMBER PRIMARY KEY,
    TABLE_NO NUMBER REFERENCES TABLE_NAME(TABLE_NO),
    MEM_NO NUMBER NOT NULL REFERENCES MEMBER(MEM_NO),
    ALERT_DATE DATE DEFAULT SYSDATE NOT NULL,
    ALERT_TYPE NUMBER CONSTRAINT ALERT_TYPE_CK CHECK(ALERT_TYPE IN('1','2','3','4','5','6')),
    ALERT_READ_NY CHAR(10) DEFAULT 'N' CONSTRAINT ALERT_READ_NY_CK CHECK(ALERT_READ_NY IN('Y','N'))
);

-- 카테고리 테이블
CREATE TABLE CATEGORY(
    CATEGORY NUMBER PRIMARY KEY,
    CATEGORY_TITLE VARCHAR2(3000) NOT NULL
);

-- 댓글 테이블
CREATE TABLE REPLY(
    REPLY_NO NUMBER PRIMARY KEY,
    REPLY_CONTENT VARCHAR2(3000) NOT NULL,
    ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL,
    MODIFY_DATE DATE DEFAULT SYSDATE,
    DEL_NY VARCHAR2(60) DEFAULT 'N' CHECK(DEL_NY IN('Y','N')) NOT NULL,
    REP_NY VARCHAR2(60) DEFAULT 'N' CHECK(REP_NY IN('Y','N')) NOT NULL,
    RECOMENT_NY VARCHAR2(60) DEFAULT 'N' CHECK(RECOMENT_NY IN('Y','N')) NOT NULL,
    REPER_NO NUMBER NOT NULL,
    FOREIGN KEY(MEM_NO) REFERENCES MEMBER(MEM_NO),
    FOREIGN KEY(TABLE_NO) REFERENCES TABLE_NAME(TABLE_NO),
    FOREIGN KEY(BOARD_NO) REFERENCES BOARD(BOARD_NO)
);

-- 참가자 목록 테이블
CREATE TABLE ENTRY_LIST(
    GROUP_NO NUMBER NOT NULL,
    ENTRY_ID VARCHAR2(60) NOT NULL,
    WAIT_NY DEFAULT 'N' CHECK(WAIT_NY IN('Y','N')) NOT NULL,
    ENTRY_DATE DATE DEFAULT SYSDATE NOT NULL,
    FOREIGN KEY(MEM_NO) REFERENCES MEMBER(MEM_NO),
    FOREIGN KEY(TABLE_NO) REFERENCES TABLE_NAME(TABLE_NO)
);

-- 실시간채팅(그룹채팅)
CREATE TABLE GROUP_MESSAGE(
    CHANNEL_NO NUMBER PRIMARY KEY,
    MESSAGE_CONTENT VARCHAR2(4000) NOT NULL,
    CREATE_AT DATE DEFAULT SYSDATE NOT NULL,
    CHANNEL_ID VARCHAR2(1000) NOT NULL,
    FOREIGN KEY(MEM_NO) REFERENCES MEMBER(MEM_NO)
);

-- 자유게시판 테이블
CREATE TABLE BOARD(
    BOARD_NO NUMBER NOT NULL,
    BOARD_TITLE VARCHAR(50) NOT NULL,
    BOARD_CONTENT VARCHAR(2000) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    MODIFY_DATE DATE DEFAULT SYSDATE NOT NULL,
    BOARD_HIT NUMBER NOT NULL,
    BOARD_FILE VARCHAR(1000),
    REP_NY VARCHAR(60) DEFAULT 'N' NOT NULL CONSTRAINT RPR_NY_CK CHECK(RPR_NY IN('Y','N')),
    DEL_NY VARCHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT DEL_NY_CK CHECK(DEL_NY IN('Y','N')),
    CATEGORY NUMBER NOT NULL REFERENCES CATEGORY,
    MEM_NO NUMBER NOT NULL REFERENCES MEMBER,
    TABLE_NO NUMBER NOT NULL REFERENCES TABLE_NAME
);

-- 공지사항 테이블
CREATE TABLE NTC(
    NTC_NO NUMBER NOT NULL,
    NTC_WRLTER VARCHAR(20) NOT NULL,
    NTC_TITLE VARCHAR(100) NOT NULL,
    NTC_CNT VARCHAR(2000) NOT NULL,
    NTC_DATE DATE DEFAULT SYSDATE NOT NULL,
    NTC_COUNT NUMBER NOT NULL,
    NTC_DEL_NY VARCHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT DEL_NY_CK CHECK(DEL_NY IN('Y','N')),
    UPDATED_AT DATE DEFAULT SYSDATE NOT NULL
);


-- 테이블 구분 컬럼명
COMMENT ON COLUMN TABLE_NAME.TABLE_NO IS '테이블번호';
COMMENT ON COLUMN TABLE_NAME.TABLE_NAME IS '테이블명';

-- MEMBER COMMENT   
COMMENT ON COLUMN MEMBER.MEM_NO IS '회원 번호';
COMMENT ON COLUMN MEMBER.MEM_TOKEN IS '토큰';
COMMENT ON COLUMN MEMBER.MEM_ID IS '아이디';
COMMENT ON COLUMN MEMBER.MEM_BIRTH IS '본인인증 확인용 생년월일';
COMMENT ON COLUMN MEMBER.MEM_PHONE IS '휴대폰 번호';
COMMENT ON COLUMN MEMBER.MEM_NAME IS '이름';
COMMENT ON COLUMN MEMBER.MEM_STATUS_NY IS '회원 상태';
COMMENT ON COLUMN MEMBER.MEM_NICKNAME IS '닉네임';
COMMENT ON COLUMN MEMBER.MEM_INTRODUCE IS '자기소개';
COMMENT ON COLUMN MEMBER.MEM_RPR_CUM IS '누적 신고수';
COMMENT ON COLUMN MEMBER.MEM_IMG IS '프로필 이미지';
COMMENT ON COLUMN MEMBER.MEM_ADMIN_NY IS '관리자 여부';

-- ALERT COMMENT
COMMENT ON COLUMN ALERT.ID_NO IS '게시물 번호';
COMMENT ON COLUMN ALERT.TABLE_NO IS '테이블 번호';
COMMENT ON COLUMN ALERT.MEM_NO IS '회원 번호';
COMMENT ON COLUMN ALERT.ALERT_DATE IS '알림 일시';
COMMENT ON COLUMN ALERT.ALERT_TYPE IS '알림 타입';
COMMENT ON COLUMN ALERT.ALERT_READ_NY IS '알림 상태';

-- 카테고리 테이블 컬럼명
COMMENT ON COLUMN CATEGORY.CATEGORY IS '카테고리';
COMMENT ON COLUMN CATEGORY.CATEGORY_TITLE IS '카테고리명';

-- 댓글 테이블 컬럼명
COMMENT ON COLUMN REPLY.REPLY_NO IS '댓글번호';
COMMENT ON COLUMN REPLY.REPLY_CONTENT IS '댓글내용';
COMMENT ON COLUMN REPLY.ENROLL_DATE IS '작성일';
COMMENT ON COLUMN REPLY.MODIFY_DATE IS '수정일자';
COMMENT ON COLUMN REPLY.DEL_NY IS '삭제여부';
COMMENT ON COLUMN REPLY.REP_NY IS '신고여부';
COMMENT ON COLUMN REPLY.RECOMMENT_NY IS '대댓글여부';
COMMENT ON COLUMN REPLY.REPER_NO IS '참조댓글';
COMMENT ON COLUMN REPLY.MEM_NO IS '참조회원번호';
COMMENT ON COLUMN REPLY.TABLE_NO IS '참조테이블번호';
COMMENT ON COLUMN REPLY.BOARD_NO IS '참조게시판번호';

-- 참가자 목록 컬럼명
COMMENT ON COLUMN ENTRY_LIST.GROUP_NO IS '모임번호';
COMMENT ON COLUMN ENTRY_LIST.ENTRY_ID IS '참가자아이디';
COMMENT ON COLUMN ENTRY_LIST.WAIT_NY IS '대기여부';
COMMENT ON COLUMN ENTRY_LIST.ENTRY_DATE IS '참가시간';
COMMENT ON COLUMN ENTRY_LIST.GROUP_NO IS '참조회원번호';
COMMENT ON COLUMN ENTRY_LIST.GROUP_NO IS '참조테이블번호';

-- 실시간채팅 컬럼명
COMMENT ON COLUMN GROUP_MESSAGE.CHANNEL_NO IS '채널번호';
COMMENT ON COLUMN GROUP_MESSAGE.MESSAGE_CONTENT IS '내용';
COMMENT ON COLUMN GROUP_MESSAGE.CREATE_AT IS '메시지 생성시간';
COMMENT ON COLUMN GROUP_MESSAGE.CHANNEL_ID IS '채널명';
COMMENT ON COLUMN GROUP_MESSAGE.MEM_NO IS '참조회원번호';

-- 자유게시판 컬럼명
COMMENT ON COLUMN BOARD.BOARD_NO IS '게시글 번호';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '게시글 내용';
COMMENT ON COLUMN BOARD.CREATE_DATE IS '작성일';
COMMENT ON COLUMN BOARD.MODIFY_DATE IS '수정일';
COMMENT ON COLUMN BOARD.BOARD_HIT IS '조회수';
COMMENT ON COLUMN BOARD.BOARD_FILE IS '첨부파일';
COMMENT ON COLUMN BOARD.REP_NY IS '신고여부';
COMMENT ON COLUMN BOARD.DEL_NY IS '삭제여부';
COMMENT ON COLUMN BOARD.CATEGORY IS '카테고리';
COMMENT ON COLUMN BOARD.MEM_NO IS '인덱스';
COMMENT ON COLUMN BOARD.TABLE_NO IS '테이블 번호';

-- 공지사항 컬럼명
COMMENT ON COLUMN NTC.NTC_NO IS '공지사항 번호';
COMMENT ON COLUMN NTC.NTC_WRLTER IS '작성자';
COMMENT ON COLUMN NTC.NTC_TITLE IS '공지제목';
COMMENT ON COLUMN NTC.NTC_CNT IS '공지내용';
COMMENT ON COLUMN NTC.NTC_DATE IS '공지등록일';
COMMENT ON COLUMN NTC.NTC_COUNT IS '조회수';
COMMENT ON COLUMN NTC.NTC_DEL_NY IS '삭제여부';
COMMENT ON COLUMN NTC.NTC_UPDATE_AT IS '수정일';
