-- 관리자계정에서 계정 생성
-- CREATE USER SOBOROO IDENTIFIED BY SOBOROO;
-- GRANT CONNECT, RESOURCE TO SOBOROO;

-- 시퀀스 삭제
DROP SEQUENCE SEQ_LNO;
DROP SEQUENCE SEQ_ALERT;
DROP SEQUENCE SEQ_REPORT;
DROP SEQUENCE SEQ_UPLOAD;
DROP SEQUENCE SEQ_BOARD;
DROP SEQUENCE SEQ_NTC;
DROP SEQUENCE SEQ_OFF_CHALLENGE_REG_NO;
DROP SEQUENCE SEQ_OFF_CHALLENGE_D_NO;
DROP SEQUENCE SEQ_OFF_GROUP_REG_NO;
DROP SEQUENCE SEQ_OFF_GROUP_ONCE_NO;
DROP SEQUENCE SEQ_ON_CHALLENGE_REG_NO;
DROP SEQUENCE SEQ_ON_CHALLENGE_D_NO;
DROP SEQUENCE SEQ_ON_GROUP_REG_NO;
DROP SEQUENCE SEQ_ON_GROUP_ONCE_NO;
DROP SEQUENCE SEQ_MEM_NO;
DROP SEQUENCE SEQ_UPLOAD_NO;

-- 테이블 삭제
DROP TABLE LINK;
DROP TABLE ALERT;
DROP TABLE REPORT;
DROP TABLE UPLOAD;
DROP TABLE GROUP_MESSAGE;
DROP TABLE REPLY;
DROP TABLE ENTRY_LIST;
DROP TABLE BOARD;
DROP TABLE NOTICE;
DROP TABLE OFFLINE_CHALLENGE_REGULAR;
DROP TABLE OFFLINE_CHALLENGE_D_DAY;
DROP TABLE OFFLINE_GROUP_REGULAR;
DROP TABLE OFFLINE_GROUP_ONCE;
DROP TABLE ONLINE_CHALLENGE_REGULAR;
DROP TABLE ONLINE_CHALLENGE_D_DAY;
DROP TABLE ONLINE_GROUP_REGULAR;
DROP TABLE ONLINE_GROUP_ONCE;
DROP TABLE LOCATION;
DROP TABLE CATEGORY;
DROP TABLE MEMBER;
DROP TABLE TABLE_NAME;
DROP TABLE GROUP_UPLOAD;

-- ----------------- TABLE_NAME -------------------

-- 테이블관리 테이블 생성
CREATE TABLE TABLE_NAME(
    TABLE_NO NUMBER PRIMARY KEY,
    TABLE_TITLE VARCHAR2(100) NOT NULL
);

-- 테이블관리 컬럼명
COMMENT ON COLUMN TABLE_NAME.TABLE_NO IS '테이블번호';
COMMENT ON COLUMN TABLE_NAME.TABLE_TITLE IS '테이블명';

-- 테이블관리 데이터 입력(필수 입력사항)
INSERT INTO TABLE_NAME(TABLE_NO, TABLE_TITLE) VALUES(1, 'MEMBER');
INSERT INTO TABLE_NAME(TABLE_NO, TABLE_TITLE) VALUES(2, 'ONLINE_GROUP_ONCE');
INSERT INTO TABLE_NAME(TABLE_NO, TABLE_TITLE) VALUES(3, 'ONLINE_GROUP_REGULAR');
INSERT INTO TABLE_NAME(TABLE_NO, TABLE_TITLE) VALUES(4, 'ONLINE_CHALLENGE_D_DAY');
INSERT INTO TABLE_NAME(TABLE_NO, TABLE_TITLE) VALUES(5, 'ONLINE_CHALLENGE_REGULAR');
INSERT INTO TABLE_NAME(TABLE_NO, TABLE_TITLE) VALUES(6, 'OFFLINE_GROUP_ONCE');
INSERT INTO TABLE_NAME(TABLE_NO, TABLE_TITLE) VALUES(7, 'OFFLINE_GROUP_REGULAR');
INSERT INTO TABLE_NAME(TABLE_NO, TABLE_TITLE) VALUES(8, 'OFFLINE_CHALLENGE_D_DAY');
INSERT INTO TABLE_NAME(TABLE_NO, TABLE_TITLE) VALUES(9, 'OFFLINE_CHALLENGE_REGULAR ');
INSERT INTO TABLE_NAME(TABLE_NO, TABLE_TITLE) VALUES(10, 'BOARD');
INSERT INTO TABLE_NAME(TABLE_NO, TABLE_TITLE) VALUES(11, 'NOTICE');
INSERT INTO TABLE_NAME(TABLE_NO, TABLE_TITLE) VALUES(12, 'REPLY');
INSERT INTO TABLE_NAME(TABLE_NO, TABLE_TITLE) VALUES(13, 'ENTRY_LIST');
INSERT INTO TABLE_NAME(TABLE_NO, TABLE_TITLE) VALUES(14, 'REPORT');
INSERT INTO TABLE_NAME(TABLE_NO, TABLE_TITLE) VALUES(15, 'ALERT');
INSERT INTO TABLE_NAME(TABLE_NO, TABLE_TITLE) VALUES(16, 'UPLOAD');
INSERT INTO TABLE_NAME(TABLE_NO, TABLE_TITLE) VALUES(17, 'CATEGORY');
INSERT INTO TABLE_NAME(TABLE_NO, TABLE_TITLE) VALUES(18, 'LOCATION');
INSERT INTO TABLE_NAME(TABLE_NO, TABLE_TITLE) VALUES(19, 'GROUP_MESSAGE');
INSERT INTO TABLE_NAME(TABLE_NO, TABLE_TITLE) VALUES(20, 'LINK');

-- ------------------- MEMBER ---------------------

-- 회원번호 부여하기 위한 시퀀스
CREATE SEQUENCE SEQ_MEM_NO
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

-- 회원 테이블 생성
CREATE TABLE MEMBER(
    MEM_NO NUMBER PRIMARY KEY,
    KAKAO_ID VARCHAR2(4000),
    MEM_EMAIL VARCHAR2(1000),
    MEM_GENDER VARCHAR2(30),
    MEM_BIRTH VARCHAR2(30),
    MEM_PHONE VARCHAR2(50) NOT NULL,
    MEM_NAME VARCHAR2(50) NOT NULL,
    MEM_STATUS NUMBER DEFAULT 1 NOT NULL CONSTRAINT MEM_STATUS_CK CHECK(MEM_STATUS IN(1,2,3,4,5)),
    MEM_NICKNAME VARCHAR2(50),
    MEM_INTRODUCE VARCHAR2(3000),
    MEM_RPR_COUNT NUMBER DEFAULT 0,
    MEM_IMG VARCHAR2(1000),
    MEM_ADULT_NY VARCHAR2(30),
    MEM_ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL,
    MEM_UPDATE_DATE DATE DEFAULT SYSDATE NOT NULL
);
    
-- 회원 컬럼명   
COMMENT ON COLUMN MEMBER.MEM_NO IS '회원 번호';
COMMENT ON COLUMN MEMBER.KAKAO_ID IS '카카오 고유값';
COMMENT ON COLUMN MEMBER.MEM_EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.MEM_GENDER IS '성별';
COMMENT ON COLUMN MEMBER.MEM_BIRTH IS '생일';
COMMENT ON COLUMN MEMBER.MEM_PHONE IS '휴대폰 번호';
COMMENT ON COLUMN MEMBER.MEM_NAME IS '이름';
COMMENT ON COLUMN MEMBER.MEM_STATUS IS '회원상태';
COMMENT ON COLUMN MEMBER.MEM_NICKNAME IS '닉네임';
COMMENT ON COLUMN MEMBER.MEM_INTRODUCE IS '자기소개';
COMMENT ON COLUMN MEMBER.MEM_RPR_COUNT IS '누적 신고수';
COMMENT ON COLUMN MEMBER.MEM_IMG IS '프로필 이미지';
COMMENT ON COLUMN MEMBER.MEM_ADULT_NY IS '성인인증';
COMMENT ON COLUMN MEMBER.MEM_ENROLL_DATE IS '회원가입일';
COMMENT ON COLUMN MEMBER.MEM_UPDATE_DATE IS '상태변경일';

-- 관리자 데이터 입력(필수 입력사항)
-- INSERT INTO MEMBER(MEM_NO, MEM_TOKEN, MEM_ID, MEM_BIRTH, MEM_PHONE, MEM_NAME, MEM_STATUS, MEM_NICKNAME) VALUES(SEQ_MEM_NO.NEXTVAL, 'TOKEN1', 'qwer9402@naver.com', '1998-05-08', '010-5049-9858', '김수진', 5, '관리자');
-- INSERT INTO MEMBER(MEM_NO, MEM_TOKEN, MEM_ID, MEM_BIRTH, MEM_PHONE, MEM_NAME, MEM_STATUS, MEM_NICKNAME) VALUES(SEQ_MEM_NO.NEXTVAL, 'TOKEN2', 'never2462@naver.com', '1996-04-02', '010-4916-4217', '최영재', 5, '관리자');
-- INSERT INTO MEMBER(MEM_NO, MEM_TOKEN, MEM_ID, MEM_BIRTH, MEM_PHONE, MEM_NAME, MEM_STATUS, MEM_NICKNAME) VALUES(SEQ_MEM_NO.NEXTVAL, 'TOKEN3', 'barkwolwol@gmail.com', '1993-02-24', '010-4130-9950', '이형근', 5, '관리자');
-- INSERT INTO MEMBER(MEM_NO, MEM_TOKEN, MEM_ID, MEM_BIRTH, MEM_PHONE, MEM_NAME, MEM_STATUS, MEM_NICKNAME) VALUES(SEQ_MEM_NO.NEXTVAL, 'TOKEN4', 'wlsdn960531@naver.com', '1996-05-31', '010-4694-3228', '박진우', 5, '관리자');
-- INSERT INTO MEMBER(MEM_NO, MEM_TOKEN, MEM_ID, MEM_BIRTH, MEM_PHONE, MEM_NAME, MEM_STATUS, MEM_NICKNAME) VALUES(SEQ_MEM_NO.NEXTVAL, 'TOKEN5', 'dlemrdl95@naver.com', '1995-04-01', '010-7307-9295', '이지원', 5, '관리자');

-- 회원 데이터 입력
-- INSERT INTO MEMBER(MEM_NO, MEM_TOKEN, MEM_ID, MEM_BIRTH, MEM_PHONE, MEM_NAME, MEM_STATUS, MEM_NICKNAME, MEM_INTRODUCE, MEM_RPR_COUNT, MEM_IMG) VALUES(SEQ_MEM_NO.NEXTVAL, 'TOKEN6', 'kh1018@gmail.com', '2000-10-18', '010-2022-2023', '김도기', 1, '디그다그', '자기소개하고 있는 중입니다.', DEFAULT, NULL);

-- -------------------- CATEGORY ---------------------

-- 카테고리 테이블 생성
CREATE TABLE CATEGORY(
    CATEGORY_NO NUMBER PRIMARY KEY,
    CATEGORY_TITLE VARCHAR2(300) NOT NULL
);

-- 카테고리 컬럼명
COMMENT ON COLUMN CATEGORY.CATEGORY_NO IS '카테고리번호';
COMMENT ON COLUMN CATEGORY.CATEGORY_TITLE IS '카테고리명';

-- 카테고리 데이터 입력(필수 입력사항)
INSERT INTO CATEGORY(CATEGORY_NO, CATEGORY_TITLE) VALUES(1, '교육/어학');
INSERT INTO CATEGORY(CATEGORY_NO, CATEGORY_TITLE) VALUES(2, '취업/자격증');
INSERT INTO CATEGORY(CATEGORY_NO, CATEGORY_TITLE) VALUES(3, '여행');
INSERT INTO CATEGORY(CATEGORY_NO, CATEGORY_TITLE) VALUES(4, '스포츠/운동');
INSERT INTO CATEGORY(CATEGORY_NO, CATEGORY_TITLE) VALUES(5, '요리/음식');
INSERT INTO CATEGORY(CATEGORY_NO, CATEGORY_TITLE) VALUES(6, '문화/예술');
INSERT INTO CATEGORY(CATEGORY_NO, CATEGORY_TITLE) VALUES(7, '영화/음악');
INSERT INTO CATEGORY(CATEGORY_NO, CATEGORY_TITLE) VALUES(8, '기타');

-- -------------------- LOCATION ---------------------

-- 지역 테이블 생성
CREATE TABLE LOCATION(
    LOCAL_NO NUMBER NOT NULL,
    SIDO VARCHAR2(100) NOT NULL,
    SIGUNGU VARCHAR2(100) NOT NULL
);

-- 지역 컬럼명
COMMENT ON COLUMN LOCATION.LOCAL_NO IS '지역번호';
COMMENT ON COLUMN LOCATION.SIDO IS '시도';
COMMENT ON COLUMN LOCATION.SIGUNGU IS '시군구';

-- 지역 데이터 입력(필수 입력사항)
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(0, '전체', '온라인');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(1, '강원도', '강릉시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(2, '강원도', '고성군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(3, '강원도', '동해시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(4, '강원도', '삼척시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(5, '강원도', '속초시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(6, '강원도', '양구군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(7, '강원도', '양양군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(8, '강원도', '영월군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(9, '강원도', '원주시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(10, '강원도', '인제군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(11, '강원도', '정선군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(12, '강원도', '철원군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(13, '강원도', '춘천시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(14, '강원도', '태백시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(15, '강원도', '평창군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(16, '강원도', '홍천군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(17, '강원도', '화천군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(18, '강원도', '횡성군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(19, '경기도', '가평군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(20, '경기도', '고양시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(24, '경기도', '과천시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(25, '경기도', '광명시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(26, '경기도', '광주시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(27, '경기도', '구리시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(28, '경기도', '군포시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(29, '경기도', '김포시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(30, '경기도', '남양주시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(31, '경기도', '동두천시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(32, '경기도', '부천시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(33, '경기도', '성남시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(36, '경기도', '수원시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(40, '경기도', '시흥시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(41, '경기도', '안산시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(43, '경기도', '안성시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(44, '경기도', '안양시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(46, '경기도', '양주시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(47, '경기도', '양평군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(48, '경기도', '여주시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(49, '경기도', '연천군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(50, '경기도', '오산시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(51, '경기도', '용인시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(54, '경기도', '의왕시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(55, '경기도', '의정부시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(56, '경기도', '이천시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(57, '경기도', '파주시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(58, '경기도', '평택시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(59, '경기도', '포천시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(60, '경기도', '하남시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(61, '경기도', '화성시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(62, '경상남도', '거제시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(63, '경상남도', '거창군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(64, '경상남도', '고성군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(65, '경상남도', '김해시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(66, '경상남도', '남해군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(67, '경상남도', '밀양시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(68, '경상남도', '사천시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(69, '경상남도', '산청군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(70, '경상남도', '양산시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(71, '경상남도', '의령군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(72, '경상남도', '진주시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(73, '경상남도', '창녕군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(74, '경상남도', '창원시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(79, '경상남도', '통영시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(80, '경상남도', '하동군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(81, '경상남도', '함안군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(82, '경상남도', '함양군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(83, '경상남도', '합천군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(84, '경상북도', '경산시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(85, '경상북도', '경주시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(86, '경상북도', '고령군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(87, '경상북도', '구미시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(88, '경상북도', '군위군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(89, '경상북도', '김천시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(90, '경상북도', '문경시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(91, '경상북도', '봉화군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(92, '경상북도', '상주시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(93, '경상북도', '성주군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(94, '경상북도', '안동시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(95, '경상북도', '영덕군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(96, '경상북도', '영양군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(97, '경상북도', '영주시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(98, '경상북도', '영천시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(99, '경상북도', '예천군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(100, '경상북도', '울릉군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(101, '경상북도', '울진군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(102, '경상북도', '의성군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(103, '경상북도', '청도군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(104, '경상북도', '청송군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(105, '경상북도', '칠곡군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(106, '경상북도', '포항시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(109, '광주광역시', '광산구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(110, '광주광역시', '남구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(111, '광주광역시', '동구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(112, '광주광역시', '북구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(113, '광주광역시', '서구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(114, '대구광역시', '남구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(115, '대구광역시', '달서구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(116, '대구광역시', '달성군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(117, '대구광역시', '동구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(118, '대구광역시', '북구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(119, '대구광역시', '서구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(120, '대구광역시', '수성구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(121, '대구광역시', '중구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(122, '대전광역시', '대덕구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(123, '대전광역시', '동구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(124, '대전광역시', '서구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(125, '대전광역시', '유성구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(126, '대전광역시', '중구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(127, '부산광역시', '강서구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(128, '부산광역시', '금정구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(129, '부산광역시', '기장군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(130, '부산광역시', '남구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(131, '부산광역시', '동구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(132, '부산광역시', '동래구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(133, '부산광역시', '부산진구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(134, '부산광역시', '북구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(135, '부산광역시', '사상구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(136, '부산광역시', '사하구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(137, '부산광역시', '서구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(138, '부산광역시', '수영구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(139, '부산광역시', '연제구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(140, '부산광역시', '영도구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(141, '부산광역시', '중구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(142, '부산광역시', '해운대구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(143, '서울특별시', '강남구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(144, '서울특별시', '강동구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(145, '서울특별시', '강북구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(146, '서울특별시', '강서구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(147, '서울특별시', '관악구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(148, '서울특별시', '광진구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(149, '서울특별시', '구로구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(150, '서울특별시', '금천구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(151, '서울특별시', '노원구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(152, '서울특별시', '도봉구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(153, '서울특별시', '동대문구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(154, '서울특별시', '동작구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(155, '서울특별시', '마포구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(156, '서울특별시', '서대문구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(157, '서울특별시', '서초구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(158, '서울특별시', '성동구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(159, '서울특별시', '성북구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(160, '서울특별시', '송파구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(161, '서울특별시', '양천구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(162, '서울특별시', '영등포구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(163, '서울특별시', '용산구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(164, '서울특별시', '은평구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(165, '서울특별시', '종로구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(166, '서울특별시', '중구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(167, '서울특별시', '중랑구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(168, '울산광역시', '남구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(169, '울산광역시', '동구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(170, '울산광역시', '북구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(171, '울산광역시', '울주군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(172, '울산광역시', '중구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(173, '인천광역시', '강화군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(174, '인천광역시', '계양구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(175, '인천광역시', '남동구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(176, '인천광역시', '동구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(177, '인천광역시', '미추홀구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(178, '인천광역시', '부평구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(179, '인천광역시', '서구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(180, '인천광역시', '연수구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(181, '인천광역시', '옹진군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(182, '인천광역시', '중구');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(183, '전라남도', '강진군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(184, '전라남도', '고흥군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(185, '전라남도', '곡성군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(186, '전라남도', '광양시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(187, '전라남도', '구례군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(188, '전라남도', '나주시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(189, '전라남도', '담양군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(190, '전라남도', '목포시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(191, '전라남도', '무안군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(192, '전라남도', '보성군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(193, '전라남도', '순천시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(194, '전라남도', '신안군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(195, '전라남도', '여수시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(196, '전라남도', '영광군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(197, '전라남도', '영암군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(198, '전라남도', '완도군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(199, '전라남도', '장성군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(200, '전라남도', '장흥군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(201, '전라남도', '진도군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(202, '전라남도', '함평군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(203, '전라남도', '해남군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(204, '전라남도', '화순군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(205, '전라북도', '고창군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(206, '전라북도', '군산시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(207, '전라북도', '김제시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(208, '전라북도', '남원시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(209, '전라북도', '무주군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(210, '전라북도', '부안군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(211, '전라북도', '순창군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(212, '전라북도', '완주군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(213, '전라북도', '익산시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(214, '전라북도', '임실군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(215, '전라북도', '장수군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(216, '전라북도', '전주시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(218, '전라북도', '정읍시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(219, '전라북도', '진안군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(220, '제주특별자치도', '서귀포시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(221, '제주특별자치도', '제주시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(222, '충청남도', '계룡시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(223, '충청남도', '공주시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(224, '충청남도', '금산군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(225, '충청남도', '논산시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(226, '충청남도', '당진시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(227, '충청남도', '보령시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(228, '충청남도', '부여군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(229, '충청남도', '서산시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(230, '충청남도', '서천군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(231, '충청남도', '아산시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(232, '충청남도', '예산군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(233, '충청남도', '천안시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(235, '충청남도', '청양군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(236, '충청남도', '태안군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(237, '충청남도', '홍성군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(238, '충청북도', '괴산군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(239, '충청북도', '단양군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(240, '충청북도', '보은군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(241, '충청북도', '영동군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(242, '충청북도', '옥천군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(243, '충청북도', '음성군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(244, '충청북도', '제천시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(245, '충청북도', '증평군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(246, '충청북도', '진천군');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(247, '충청북도', '청주시');
INSERT INTO LOCATION(LOCAL_NO, SIDO, SIGUNGU) VALUES(251, '충청북도', '충주시');

-- -------------- ONLINE_GROUP_ONCE ------------------

-- 그룹번호 부여하기 위한 시퀀스 생성(온라인일반단기)
CREATE SEQUENCE SEQ_ON_GROUP_ONCE_NO
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

-- 온라인일반단기 테이블 생성
CREATE TABLE ONLINE_GROUP_ONCE(
    NO NUMBER CONSTRAINT ON_GROUP_ONCE_NO_PK PRIMARY KEY,
    TITLE VARCHAR2(4000) NOT NULL,
    ID VARCHAR2(100) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    PHONE VARCHAR2(40) NOT NULL,
    SIMPLE VARCHAR2(400) NOT NULL,
    ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL,
    MODIFY_DATE DATE DEFAULT SYSDATE,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    START_ENTER DATE NOT NULL,
    END_ENTER DATE NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    ADDRESS VARCHAR2(4000),
    ADDRESS_DETAIL VARCHAR2(4000),
    DISPLAY_NY VARCHAR2(100),
    EVENT_PASSWORD VARCHAR2(4000),
    HASH_TAG VARCHAR2(4000),
    DEL_NY VARCHAR2(10) DEFAULT 'N' NOT NULL CHECK(DEL_NY IN('N', 'Y')),   
    REP_NY VARCHAR2(10) DEFAULT 'N' NOT NULL CHECK(REP_NY IN('N', 'Y')),
    URL VARCHAR2(4000),
    MAX NUMBER NOT NULL,
    MAX_ACCESS VARCHAR2(10),
    ADULT_ACCESS VARCHAR2(10),
    CATEGORY_NO NUMBER NOT NULL,
    MEM_NO NUMBER NOT NULL,
    TABLE_NO NUMBER DEFAULT 2 NOT NULL REFERENCES TABLE_NAME,
    ATTEND_PASSWORD VARCHAR2(4000),
    COUNT NUMBER DEFAULT '0' NOT NULL,
    STATUS VARCHAR2(10) DEFAULT 'Y' NOT NULL,
    THUMBNAIL VARCHAR2(4000)
);

-- 온라인일반단기 컬럼명
COMMENT ON COLUMN ONLINE_GROUP_ONCE.NO IS '모임번호';
COMMENT ON COLUMN ONLINE_GROUP_ONCE.TITLE IS '모임명';
COMMENT ON COLUMN ONLINE_GROUP_ONCE.ID IS '개설자';
COMMENT ON COLUMN ONLINE_GROUP_ONCE.NAME IS '담당자명';
COMMENT ON COLUMN ONLINE_GROUP_ONCE.EMAIL IS '이메일';
COMMENT ON COLUMN ONLINE_GROUP_ONCE.PHONE IS '전화번호';
COMMENT ON COLUMN ONLINE_GROUP_ONCE.SIMPLE IS '간단소개';
COMMENT ON COLUMN ONLINE_GROUP_ONCE.ENROLL_DATE IS '등록일자';
COMMENT ON COLUMN ONLINE_GROUP_ONCE.MODIFY_DATE IS '수정일자';
COMMENT ON COLUMN ONLINE_GROUP_ONCE.START_DATE IS '모임시작일자';
COMMENT ON COLUMN ONLINE_GROUP_ONCE.END_DATE IS '모임종료일자';
COMMENT ON COLUMN ONLINE_GROUP_ONCE.START_ENTER IS '접수시작일자';
COMMENT ON COLUMN ONLINE_GROUP_ONCE.END_ENTER IS '접수종료일자';
COMMENT ON COLUMN ONLINE_GROUP_ONCE.CONTENT IS '상세내용';
COMMENT ON COLUMN ONLINE_GROUP_ONCE.ADDRESS IS '주소';
COMMENT ON COLUMN ONLINE_GROUP_ONCE.ADDRESS_DETAIL IS '상세주소';
COMMENT ON COLUMN ONLINE_GROUP_ONCE.DISPLAY_NY IS '노출여부';
COMMENT ON COLUMN ONLINE_GROUP_ONCE.EVENT_PASSWORD IS '비밀번호';
COMMENT ON COLUMN ONLINE_GROUP_ONCE.HASH_TAG IS '해시태그';
COMMENT ON COLUMN ONLINE_GROUP_ONCE.DEL_NY IS '삭제여부';
COMMENT ON COLUMN ONLINE_GROUP_ONCE.REP_NY IS '신고여부';
COMMENT ON COLUMN ONLINE_GROUP_ONCE.URL IS 'url';
COMMENT ON COLUMN ONLINE_GROUP_ONCE.MAX IS '정원';
COMMENT ON COLUMN ONLINE_GROUP_ONCE.MAX_ACCESS IS '정원초과허용여부';
COMMENT ON COLUMN ONLINE_GROUP_ONCE.ADULT_ACCESS IS '청소년접근제한여부';
COMMENT ON COLUMN ONLINE_GROUP_ONCE.CATEGORY_NO IS '카테고리';
COMMENT ON COLUMN ONLINE_GROUP_ONCE.MEM_NO IS '회원번호';
COMMENT ON COLUMN ONLINE_GROUP_ONCE.TABLE_NO IS '테이블번호';
COMMENT ON COLUMN ONLINE_GROUP_ONCE.ATTEND_PASSWORD IS '출석확인용비밀번호';
COMMENT ON COLUMN ONLINE_GROUP_ONCE.COUNT IS '조회수';
COMMENT ON COLUMN ONLINE_GROUP_ONCE.STATUS IS '상태';
COMMENT ON COLUMN ONLINE_GROUP_ONCE.THUMBNAIL IS '상태';

-- ------------- ONLINE_GROUP_REGULAR ----------------

-- 그룹번호 부여하기 위한 시퀀스 생성(온라인일반정기)
CREATE SEQUENCE SEQ_ON_GROUP_REG_NO
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

-- 온라인일반정기 테이블 생성
CREATE TABLE ONLINE_GROUP_REGULAR(
   NO NUMBER CONSTRAINT ON_GROUP_REG_NO_PK PRIMARY KEY,
   TITLE VARCHAR2(100) NOT NULL,
   ID VARCHAR2(100) NOT NULL,
   NAME VARCHAR2(100) NOT NULL,
   EMAIL VARCHAR2(100) NOT NULL,
   PHONE VARCHAR2(40) NOT NULL,
   SIMPLE VARCHAR2(400) NOT NULL,
   ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL,
   MODIFY_DATE DATE DEFAULT SYSDATE,
   START_DATE DATE NOT NULL,
   END_DATE DATE NOT NULL,
   START_ENTER DATE NOT NULL,
   END_ENTER DATE NOT NULL,
   CONTENT VARCHAR2(4000) NOT NULL,
   ADDRESS VARCHAR2(4000),
   ADDRESS_DETAIL VARCHAR2(4000),
    DISPLAY_NY VARCHAR2(100) NOT NULL,
    EVENT_PASSWORD VARCHAR2(4000),
   HASH_TAG VARCHAR2(4000),
   DEL_NY VARCHAR2(10) DEFAULT 'N' NOT NULL CHECK(DEL_NY IN('N', 'Y')),   
   REP_NY VARCHAR2(10) DEFAULT 'N' NOT NULL CHECK(REP_NY IN('N', 'Y')),
   URL VARCHAR2(4000),
   MAX NUMBER NOT NULL,
   MAX_ACCESS VARCHAR2(10) NOT NULL,
   ADULT_ACCESS VARCHAR2(10) NOT NULL,
   CATEGORY_NO NUMBER NOT NULL,
   MEM_NO NUMBER NOT NULL,
   TABLE_NO NUMBER DEFAULT 2 NOT NULL REFERENCES TABLE_NAME,
    ATTEND_PASSWORD VARCHAR2(4000),
   COUNT NUMBER DEFAULT '0' NOT NULL,
   STATUS VARCHAR2(10) DEFAULT 'Y' NOT NULL
);

-- 온라인일반정기 컬럼명
COMMENT ON COLUMN ONLINE_GROUP_REGULAR.NO IS '모임번호';
COMMENT ON COLUMN ONLINE_GROUP_REGULAR.TITLE IS '모임명';
COMMENT ON COLUMN ONLINE_GROUP_REGULAR.ID IS '개설자';
COMMENT ON COLUMN ONLINE_GROUP_REGULAR.EMAIL IS '이메일';
COMMENT ON COLUMN ONLINE_GROUP_REGULAR.NAME IS '담당자명';
COMMENT ON COLUMN ONLINE_GROUP_REGULAR.PHONE IS '전화번호';
COMMENT ON COLUMN ONLINE_GROUP_REGULAR.SIMPLE IS '간단소개';
COMMENT ON COLUMN ONLINE_GROUP_REGULAR.ENROLL_DATE IS '등록일자';
COMMENT ON COLUMN ONLINE_GROUP_REGULAR.MODIFY_DATE IS '수정일자';
COMMENT ON COLUMN ONLINE_GROUP_REGULAR.START_DATE IS '모임시작일자';
COMMENT ON COLUMN ONLINE_GROUP_REGULAR.END_DATE IS '모임종료일자';
COMMENT ON COLUMN ONLINE_GROUP_REGULAR.START_ENTER IS '접수시작일자';
COMMENT ON COLUMN ONLINE_GROUP_REGULAR.END_ENTER IS '접수종료일자';
COMMENT ON COLUMN ONLINE_GROUP_REGULAR.CONTENT IS '상세내용';
COMMENT ON COLUMN ONLINE_GROUP_REGULAR.ADDRESS IS '주소';
COMMENT ON COLUMN ONLINE_GROUP_REGULAR.ADDRESS_DETAIL IS '상세주소';
COMMENT ON COLUMN ONLINE_GROUP_REGULAR.DISPLAY_NY IS '노출여부';
COMMENT ON COLUMN ONLINE_GROUP_REGULAR.EVENT_PASSWORD IS '비밀번호';
COMMENT ON COLUMN ONLINE_GROUP_REGULAR.HASH_TAG IS '해시태그';
COMMENT ON COLUMN ONLINE_GROUP_REGULAR.DEL_NY IS '삭제여부';
COMMENT ON COLUMN ONLINE_GROUP_REGULAR.REP_NY IS '신고여부';
COMMENT ON COLUMN ONLINE_GROUP_REGULAR.URL IS 'url';
COMMENT ON COLUMN ONLINE_GROUP_REGULAR.MAX IS '정원';
COMMENT ON COLUMN ONLINE_GROUP_REGULAR.MAX_ACCESS IS '정원초과허용여부';
COMMENT ON COLUMN ONLINE_GROUP_REGULAR.ADULT_ACCESS IS '청소년접근제한여부';
COMMENT ON COLUMN ONLINE_GROUP_REGULAR.CATEGORY_NO IS '카테고리';
COMMENT ON COLUMN ONLINE_GROUP_REGULAR.MEM_NO IS '회원번호';
COMMENT ON COLUMN ONLINE_GROUP_REGULAR.TABLE_NO IS '테이블번호';
COMMENT ON COLUMN ONLINE_GROUP_REGULAR.ATTEND_PASSWORD IS '출석확인용비밀번호';
COMMENT ON COLUMN ONLINE_GROUP_REGULAR.COUNT IS '조회수';
COMMENT ON COLUMN ONLINE_GROUP_REGULAR.STATUS IS '상태';

-- ------------ ONLINE_CHALLENGE_D_DAY ---------------

-- 그룹번호 부여하기 위한 시퀀스 생성(온라인목표디데이)
CREATE SEQUENCE SEQ_ON_CHALLENGE_D_NO
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

-- 온라인목표디데이 테이블 생성
CREATE TABLE ONLINE_CHALLENGE_D_DAY(
   NO NUMBER CONSTRAINT ON_CHALL_D_NO_PK PRIMARY KEY,
   TITLE VARCHAR2(100) NOT NULL,
   ID VARCHAR2(100) NOT NULL,
   NAME VARCHAR2(100) NOT NULL,
   EMAIL VARCHAR2(100) NOT NULL,
   PHONE VARCHAR2(40) NOT NULL,
   SIMPLE VARCHAR2(400) NOT NULL,
   ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL,
   MODIFY_DATE DATE DEFAULT SYSDATE,
   START_DATE DATE NOT NULL,
   END_DATE DATE NOT NULL,
   START_ENTER DATE NOT NULL,
   END_ENTER DATE NOT NULL,
   ACHIEVE_NY VARCHAR2(40) DEFAULT 'N' NOT NULL CHECK(ACHIEVE_NY IN('N', 'Y')),
   CONTENT VARCHAR2(4000) NOT NULL,
   ADDRESS VARCHAR2(4000),
   ADDRESS_DETAIL VARCHAR2(4000),
    DISPLAY_NY VARCHAR2(100) NOT NULL,
    EVENT_PASSWORD VARCHAR2(4000),
   HASH_TAG VARCHAR2(4000),
   DEL_NY VARCHAR2(10) DEFAULT 'N' NOT NULL CHECK(DEL_NY IN('N', 'Y')),   
   REP_NY VARCHAR2(10) DEFAULT 'N' NOT NULL CHECK(REP_NY IN('N', 'Y')),
   URL VARCHAR2(4000),
   MAX NUMBER NOT NULL,
   MAX_ACCESS VARCHAR2(10) NOT NULL,
   ADULT_ACCESS VARCHAR2(10) NOT NULL,
   CATEGORY_NO NUMBER NOT NULL,
   MEM_NO NUMBER NOT NULL,
   TABLE_NO NUMBER DEFAULT 2 NOT NULL REFERENCES TABLE_NAME,
    ATTEND_PASSWORD VARCHAR2(4000),
   COUNT NUMBER DEFAULT '0' NOT NULL,
   STATUS VARCHAR2(10) DEFAULT 'Y' NOT NULL
);

-- 온라인목표디데이 컬럼명
COMMENT ON COLUMN ONLINE_CHALLENGE_D_DAY.NO IS '모임번호';
COMMENT ON COLUMN ONLINE_CHALLENGE_D_DAY.TITLE IS '모임명';
COMMENT ON COLUMN ONLINE_CHALLENGE_D_DAY.ID IS '개설자';
COMMENT ON COLUMN ONLINE_CHALLENGE_D_DAY.NAME IS '담당자명';
COMMENT ON COLUMN ONLINE_CHALLENGE_D_DAY.EMAIL IS '이메일';
COMMENT ON COLUMN ONLINE_CHALLENGE_D_DAY.PHONE IS '전화번호';
COMMENT ON COLUMN ONLINE_CHALLENGE_D_DAY.SIMPLE IS '간단소개';
COMMENT ON COLUMN ONLINE_CHALLENGE_D_DAY.ENROLL_DATE IS '등록일자';
COMMENT ON COLUMN ONLINE_CHALLENGE_D_DAY.MODIFY_DATE IS '수정일자';
COMMENT ON COLUMN ONLINE_CHALLENGE_D_DAY.START_DATE IS '모임시작일자';
COMMENT ON COLUMN ONLINE_CHALLENGE_D_DAY.END_DATE IS '모임종료일자';
COMMENT ON COLUMN ONLINE_CHALLENGE_D_DAY.START_ENTER IS '접수시작일자';
COMMENT ON COLUMN ONLINE_CHALLENGE_D_DAY.END_ENTER IS '접수종료일자';
COMMENT ON COLUMN ONLINE_CHALLENGE_D_DAY.ACHIEVE_NY IS '달성여부';
COMMENT ON COLUMN ONLINE_CHALLENGE_D_DAY.CONTENT IS '상세내용';
COMMENT ON COLUMN ONLINE_CHALLENGE_D_DAY.ADDRESS IS '주소';
COMMENT ON COLUMN ONLINE_CHALLENGE_D_DAY.ADDRESS_DETAIL IS '상세주소';
COMMENT ON COLUMN ONLINE_CHALLENGE_D_DAY.DISPLAY_NY IS '노출여부';
COMMENT ON COLUMN ONLINE_CHALLENGE_D_DAY.EVENT_PASSWORD IS '비밀번호';
COMMENT ON COLUMN ONLINE_CHALLENGE_D_DAY.HASH_TAG IS '해시태그';
COMMENT ON COLUMN ONLINE_CHALLENGE_D_DAY.DEL_NY IS '삭제여부';
COMMENT ON COLUMN ONLINE_CHALLENGE_D_DAY.REP_NY IS '신고여부';
COMMENT ON COLUMN ONLINE_CHALLENGE_D_DAY.URL IS 'url';
COMMENT ON COLUMN ONLINE_CHALLENGE_D_DAY.MAX IS '정원';
COMMENT ON COLUMN ONLINE_CHALLENGE_D_DAY.MAX_ACCESS IS '정원초과허용여부';
COMMENT ON COLUMN ONLINE_CHALLENGE_D_DAY.ADULT_ACCESS IS '청소년접근제한여부';
COMMENT ON COLUMN ONLINE_CHALLENGE_D_DAY.CATEGORY_NO IS '카테고리';
COMMENT ON COLUMN ONLINE_CHALLENGE_D_DAY.MEM_NO IS '회원번호';
COMMENT ON COLUMN ONLINE_CHALLENGE_D_DAY.TABLE_NO IS '테이블번호';
COMMENT ON COLUMN ONLINE_CHALLENGE_D_DAY.ATTEND_PASSWORD IS '출석확인용비밀번호';
COMMENT ON COLUMN ONLINE_CHALLENGE_D_DAY.COUNT IS '조회수';
COMMENT ON COLUMN ONLINE_CHALLENGE_D_DAY.STATUS IS '상태';

-- ------------ ONLINE_CHALLENGE_REGULAR -------------

-- 그룹번호 부여하기 위한 시퀀스 생성(온라인목표정기)
CREATE SEQUENCE SEQ_ON_CHALLENGE_REG_NO
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

-- 온라인목표정기 테이블 생성
CREATE TABLE ONLINE_CHALLENGE_REGULAR(
   NO NUMBER CONSTRAINT ON_CHALLENGE_REG_NO_PK PRIMARY KEY,
   TITLE VARCHAR2(100) NOT NULL,
   ID VARCHAR2(100) NOT NULL,
   NAME VARCHAR2(100) NOT NULL,
   EMAIL VARCHAR2(100) NOT NULL,
   PHONE VARCHAR2(40) NOT NULL,
   SIMPLE VARCHAR2(400) NOT NULL,
   ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL,
   MODIFY_DATE DATE DEFAULT SYSDATE,
   START_DATE DATE NOT NULL,
   END_DATE DATE NOT NULL,
   START_ENTER DATE NOT NULL,
   END_ENTER DATE NOT NULL,
   ACHIEVE_NY VARCHAR2(40) DEFAULT 'N' NOT NULL CHECK(ACHIEVE_NY IN('N', 'Y')),
   CONTENT VARCHAR2(4000) NOT NULL,
   ADDRESS VARCHAR2(4000),
   ADDRESS_DETAIL VARCHAR2(4000),
    DISPLAY_NY VARCHAR2(100) NOT NULL,
    EVENT_PASSWORD VARCHAR2(4000),
   HASH_TAG VARCHAR2(4000),
   DEL_NY VARCHAR2(10) DEFAULT 'N' NOT NULL CHECK(DEL_NY IN('N', 'Y')),   
   REP_NY VARCHAR2(10) DEFAULT 'N' NOT NULL CHECK(REP_NY IN('N', 'Y')),
   URL VARCHAR2(4000),
   MAX NUMBER NOT NULL,
   MAX_ACCESS VARCHAR2(10) NOT NULL,
   ADULT_ACCESS VARCHAR2(10) NOT NULL,
   CATEGORY_NO NUMBER NOT NULL,
   MEM_NO NUMBER NOT NULL,
   TABLE_NO NUMBER DEFAULT 2 NOT NULL REFERENCES TABLE_NAME,
    ATTEND_PASSWORD VARCHAR2(4000),
   COUNT NUMBER DEFAULT '0' NOT NULL,
   STATUS VARCHAR2(10) DEFAULT 'Y' NOT NULL
);

-- 온라인목표정기 컬럼명
COMMENT ON COLUMN ONLINE_CHALLENGE_REGULAR.NO IS '모임번호';
COMMENT ON COLUMN ONLINE_CHALLENGE_REGULAR.TITLE IS '모임명';
COMMENT ON COLUMN ONLINE_CHALLENGE_REGULAR.ID IS '개설자';
COMMENT ON COLUMN ONLINE_CHALLENGE_REGULAR.NAME IS '담당자명';
COMMENT ON COLUMN ONLINE_CHALLENGE_REGULAR.EMAIL IS '이메일';
COMMENT ON COLUMN ONLINE_CHALLENGE_REGULAR.PHONE IS '전화번호';
COMMENT ON COLUMN ONLINE_CHALLENGE_REGULAR.SIMPLE IS '간단소개';
COMMENT ON COLUMN ONLINE_CHALLENGE_REGULAR.ENROLL_DATE IS '등록일자';
COMMENT ON COLUMN ONLINE_CHALLENGE_REGULAR.MODIFY_DATE IS '수정일자';
COMMENT ON COLUMN ONLINE_CHALLENGE_REGULAR.START_DATE IS '모임시작일자';
COMMENT ON COLUMN ONLINE_CHALLENGE_REGULAR.END_DATE IS '모임종료일자';
COMMENT ON COLUMN ONLINE_CHALLENGE_REGULAR.START_ENTER IS '접수시작일자';
COMMENT ON COLUMN ONLINE_CHALLENGE_REGULAR.END_ENTER IS '접수종료일자';
COMMENT ON COLUMN ONLINE_CHALLENGE_REGULAR.ACHIEVE_NY IS '달성여부';
COMMENT ON COLUMN ONLINE_CHALLENGE_REGULAR.CONTENT IS '상세내용';
COMMENT ON COLUMN ONLINE_CHALLENGE_REGULAR.ADDRESS IS '주소';
COMMENT ON COLUMN ONLINE_CHALLENGE_REGULAR.ADDRESS_DETAIL IS '상세주소';
COMMENT ON COLUMN ONLINE_CHALLENGE_REGULAR.DISPLAY_NY IS '노출여부';
COMMENT ON COLUMN ONLINE_CHALLENGE_REGULAR.EVENT_PASSWORD IS '비밀번호';
COMMENT ON COLUMN ONLINE_CHALLENGE_REGULAR.HASH_TAG IS '해시태그';
COMMENT ON COLUMN ONLINE_CHALLENGE_REGULAR.DEL_NY IS '삭제여부';
COMMENT ON COLUMN ONLINE_CHALLENGE_REGULAR.REP_NY IS '신고여부';
COMMENT ON COLUMN ONLINE_CHALLENGE_REGULAR.URL IS 'url';
COMMENT ON COLUMN ONLINE_CHALLENGE_REGULAR.MAX IS '정원';
COMMENT ON COLUMN ONLINE_CHALLENGE_REGULAR.MAX_ACCESS IS '정원초과허용여부';
COMMENT ON COLUMN ONLINE_CHALLENGE_REGULAR.ADULT_ACCESS IS '청소년접근제한여부';
COMMENT ON COLUMN ONLINE_CHALLENGE_REGULAR.CATEGORY_NO IS '카테고리';
COMMENT ON COLUMN ONLINE_CHALLENGE_REGULAR.MEM_NO IS '회원번호';
COMMENT ON COLUMN ONLINE_CHALLENGE_REGULAR.TABLE_NO IS '테이블번호';
COMMENT ON COLUMN ONLINE_CHALLENGE_REGULAR.ATTEND_PASSWORD IS '출석확인용비밀번호';
COMMENT ON COLUMN ONLINE_CHALLENGE_REGULAR.COUNT IS '조회수';
COMMENT ON COLUMN ONLINE_CHALLENGE_REGULAR.STATUS IS '상태';

-- -------------- OFFLINE_GROUP_ONCE -----------------

-- 그룹번호 부여하기 위한 시퀀스 생성(오프라인일반단기)
CREATE SEQUENCE SEQ_OFF_GROUP_ONCE_NO
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

-- 오프라인일반단기 테이블 생성
CREATE TABLE OFFLINE_GROUP_ONCE(
   NO NUMBER CONSTRAINT OFF_GROUP_ONCE_NO_PK PRIMARY KEY,
   TITLE VARCHAR2(4000) NOT NULL,
   ID VARCHAR2(100) NOT NULL,
   NAME VARCHAR2(100) NOT NULL,
   EMAIL VARCHAR2(100) NOT NULL,
   PHONE VARCHAR2(40) NOT NULL,
   SIMPLE VARCHAR2(400) NOT NULL,
   ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL,
   MODIFY_DATE DATE DEFAULT SYSDATE,
   START_DATE DATE NOT NULL,
   END_DATE DATE NOT NULL,
   START_ENTER DATE NOT NULL,
   END_ENTER DATE NOT NULL,
   CONTENT VARCHAR2(4000) NOT NULL,
   ADDRESS VARCHAR2(4000),
   ADDRESS_DETAIL VARCHAR2(4000),
    DISPLAY_NY VARCHAR2(100),
    EVENT_PASSWORD VARCHAR2(4000),
   HASH_TAG VARCHAR2(4000),
   DEL_NY VARCHAR2(10) DEFAULT 'N' NOT NULL CHECK(DEL_NY IN('N', 'Y')),   
   REP_NY VARCHAR2(10) DEFAULT 'N' NOT NULL CHECK(REP_NY IN('N', 'Y')),
   URL VARCHAR2(4000),
   MAX NUMBER NOT NULL,
   MAX_ACCESS VARCHAR2(10),
   ADULT_ACCESS VARCHAR2(10),
   CATEGORY_NO NUMBER NOT NULL,
   MEM_NO NUMBER NOT NULL,
   TABLE_NO NUMBER DEFAULT 2 NOT NULL REFERENCES TABLE_NAME,
    ATTEND_PASSWORD VARCHAR2(4000),
   COUNT NUMBER DEFAULT '0' NOT NULL,
   STATUS VARCHAR2(10) DEFAULT 'Y' NOT NULL,
   THUMBNAIL VARCHAR2(4000)
);

-- 오프라인일반단기 컬럼명
COMMENT ON COLUMN OFFLINE_GROUP_ONCE.NO IS '모임번호';
COMMENT ON COLUMN OFFLINE_GROUP_ONCE.TITLE IS '모임명';
COMMENT ON COLUMN OFFLINE_GROUP_ONCE.ID IS '개설자';
COMMENT ON COLUMN OFFLINE_GROUP_ONCE.NAME IS '담당자명';
COMMENT ON COLUMN OFFLINE_GROUP_ONCE.EMAIL IS '이메일';
COMMENT ON COLUMN OFFLINE_GROUP_ONCE.PHONE IS '전화번호';
COMMENT ON COLUMN OFFLINE_GROUP_ONCE.SIMPLE IS '간단소개';
COMMENT ON COLUMN OFFLINE_GROUP_ONCE.ENROLL_DATE IS '등록일자';
COMMENT ON COLUMN OFFLINE_GROUP_ONCE.MODIFY_DATE IS '수정일자';
COMMENT ON COLUMN OFFLINE_GROUP_ONCE.START_DATE IS '모임시작일자';
COMMENT ON COLUMN OFFLINE_GROUP_ONCE.END_DATE IS '모임종료일자';
COMMENT ON COLUMN OFFLINE_GROUP_ONCE.START_ENTER IS '접수시작일자';
COMMENT ON COLUMN OFFLINE_GROUP_ONCE.END_ENTER IS '접수종료일자';
COMMENT ON COLUMN OFFLINE_GROUP_ONCE.CONTENT IS '상세내용';
COMMENT ON COLUMN OFFLINE_GROUP_ONCE.ADDRESS IS '주소';
COMMENT ON COLUMN OFFLINE_GROUP_ONCE.ADDRESS_DETAIL IS '상세주소';
COMMENT ON COLUMN OFFLINE_GROUP_ONCE.DISPLAY_NY IS '노출여부';
COMMENT ON COLUMN OFFLINE_GROUP_ONCE.EVENT_PASSWORD IS '비밀번호';
COMMENT ON COLUMN OFFLINE_GROUP_ONCE.HASH_TAG IS '해시태그';
COMMENT ON COLUMN OFFLINE_GROUP_ONCE.DEL_NY IS '삭제여부';
COMMENT ON COLUMN OFFLINE_GROUP_ONCE.REP_NY IS '신고여부';
COMMENT ON COLUMN OFFLINE_GROUP_ONCE.URL IS 'url';
COMMENT ON COLUMN OFFLINE_GROUP_ONCE.MAX IS '정원';
COMMENT ON COLUMN OFFLINE_GROUP_ONCE.MAX_ACCESS IS '정원초과허용여부';
COMMENT ON COLUMN OFFLINE_GROUP_ONCE.ADULT_ACCESS IS '청소년접근제한여부';
COMMENT ON COLUMN OFFLINE_GROUP_ONCE.CATEGORY_NO IS '카테고리';
COMMENT ON COLUMN OFFLINE_GROUP_ONCE.MEM_NO IS '회원번호';
COMMENT ON COLUMN OFFLINE_GROUP_ONCE.TABLE_NO IS '테이블번호';
COMMENT ON COLUMN OFFLINE_GROUP_ONCE.ATTEND_PASSWORD IS '출석확인용비밀번호';
COMMENT ON COLUMN OFFLINE_GROUP_ONCE.COUNT IS '조회수';
COMMENT ON COLUMN OFFLINE_GROUP_ONCE.STATUS IS '상태';
COMMENT ON COLUMN OFFLINE_GROUP_ONCE.THUMBNAIL IS '대표이미지';
-- ------------- OFFLINE_GROUP_REGULAR ---------------

-- 그룹번호 부여하기 위한 시퀀스 생성(오프라인일반정기)
CREATE SEQUENCE SEQ_OFF_GROUP_REG_NO
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

-- 오프라인일반정기 테이블 생성
CREATE TABLE OFFLINE_GROUP_REGULAR(
   NO NUMBER CONSTRAINT OFF_GROUP_REG_NO_PK PRIMARY KEY,
   TITLE VARCHAR2(100) NOT NULL,
   ID VARCHAR2(100) NOT NULL,
   NAME VARCHAR2(100) NOT NULL,
   EMAIL VARCHAR2(100) NOT NULL,
   PHONE VARCHAR2(40) NOT NULL,
   SIMPLE VARCHAR2(400) NOT NULL,
   ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL,
   MODIFY_DATE DATE DEFAULT SYSDATE,
   START_DATE DATE NOT NULL,
   END_DATE DATE NOT NULL,
   START_ENTER DATE NOT NULL,
   END_ENTER DATE NOT NULL,
   CONTENT VARCHAR2(4000) NOT NULL,
   ADDRESS VARCHAR2(4000),
   ADDRESS_DETAIL VARCHAR2(4000),
    DISPLAY_NY VARCHAR2(100) NOT NULL,
    EVENT_PASSWORD VARCHAR2(4000),
   HASH_TAG VARCHAR2(4000),
   DEL_NY VARCHAR2(10) DEFAULT 'N' NOT NULL CHECK(DEL_NY IN('N', 'Y')),   
   REP_NY VARCHAR2(10) DEFAULT 'N' NOT NULL CHECK(REP_NY IN('N', 'Y')),
   URL VARCHAR2(4000),
   MAX NUMBER NOT NULL,
   MAX_ACCESS VARCHAR2(10) NOT NULL,
   ADULT_ACCESS VARCHAR2(10) NOT NULL,
   CATEGORY_NO NUMBER NOT NULL,
   MEM_NO NUMBER NOT NULL,
   TABLE_NO NUMBER DEFAULT 2 NOT NULL REFERENCES TABLE_NAME,
    ATTEND_PASSWORD VARCHAR2(4000),
   COUNT NUMBER DEFAULT '0' NOT NULL,
   STATUS VARCHAR2(10) DEFAULT 'Y' NOT NULL
);

-- 오프라인일반정기 컬럼명
COMMENT ON COLUMN OFFLINE_GROUP_REGULAR.NO IS '모임번호';
COMMENT ON COLUMN OFFLINE_GROUP_REGULAR.TITLE IS '모임명';
COMMENT ON COLUMN OFFLINE_GROUP_REGULAR.ID IS '개설자';
COMMENT ON COLUMN OFFLINE_GROUP_REGULAR.NAME IS '담당자명';
COMMENT ON COLUMN OFFLINE_GROUP_REGULAR.EMAIL IS '이메일';
COMMENT ON COLUMN OFFLINE_GROUP_REGULAR.PHONE IS '전화번호';
COMMENT ON COLUMN OFFLINE_GROUP_REGULAR.SIMPLE IS '간단소개';
COMMENT ON COLUMN OFFLINE_GROUP_REGULAR.ENROLL_DATE IS '등록일자';
COMMENT ON COLUMN OFFLINE_GROUP_REGULAR.MODIFY_DATE IS '수정일자';
COMMENT ON COLUMN OFFLINE_GROUP_REGULAR.START_DATE IS '모임시작일자';
COMMENT ON COLUMN OFFLINE_GROUP_REGULAR.END_DATE IS '모임종료일자';
COMMENT ON COLUMN OFFLINE_GROUP_REGULAR.START_ENTER IS '접수시작일자';
COMMENT ON COLUMN OFFLINE_GROUP_REGULAR.END_ENTER IS '접수종료일자';
COMMENT ON COLUMN OFFLINE_GROUP_REGULAR.CONTENT IS '상세내용';
COMMENT ON COLUMN OFFLINE_GROUP_REGULAR.ADDRESS IS '주소';
COMMENT ON COLUMN OFFLINE_GROUP_REGULAR.ADDRESS_DETAIL IS '상세주소';
COMMENT ON COLUMN OFFLINE_GROUP_REGULAR.DISPLAY_NY IS '노출여부';
COMMENT ON COLUMN OFFLINE_GROUP_REGULAR.EVENT_PASSWORD IS '비밀번호';
COMMENT ON COLUMN OFFLINE_GROUP_REGULAR.HASH_TAG IS '해시태그';
COMMENT ON COLUMN OFFLINE_GROUP_REGULAR.DEL_NY IS '삭제여부';
COMMENT ON COLUMN OFFLINE_GROUP_REGULAR.REP_NY IS '신고여부';
COMMENT ON COLUMN OFFLINE_GROUP_REGULAR.URL IS 'url';
COMMENT ON COLUMN OFFLINE_GROUP_REGULAR.MAX IS '정원';
COMMENT ON COLUMN OFFLINE_GROUP_REGULAR.MAX_ACCESS IS '정원초과허용여부';
COMMENT ON COLUMN OFFLINE_GROUP_REGULAR.ADULT_ACCESS IS '청소년접근제한여부';
COMMENT ON COLUMN OFFLINE_GROUP_REGULAR.CATEGORY_NO IS '카테고리';
COMMENT ON COLUMN OFFLINE_GROUP_REGULAR.MEM_NO IS '회원번호';
COMMENT ON COLUMN OFFLINE_GROUP_REGULAR.TABLE_NO IS '테이블번호';
COMMENT ON COLUMN OFFLINE_GROUP_REGULAR.ATTEND_PASSWORD IS '출석확인용비밀번호';
COMMENT ON COLUMN OFFLINE_GROUP_REGULAR.COUNT IS '조회수';
COMMENT ON COLUMN OFFLINE_GROUP_REGULAR.STATUS IS '상태';

-- ------------ OFFLINE_CHALLENGE_D_DAY --------------

-- 그룹번호 부여하기 위한 시퀀스 생성(오프라인목표디데이)
CREATE SEQUENCE SEQ_OFF_CHALLENGE_D_NO
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

-- 오프라인목표디데이 테이블 생성
CREATE TABLE OFFLINE_CHALLENGE_D_DAY(
   NO NUMBER CONSTRAINT OFF_CHALLENGE_D_NO_PK PRIMARY KEY,
   TITLE VARCHAR2(100) NOT NULL,
   ID VARCHAR2(100) NOT NULL,
   NAME VARCHAR2(100) NOT NULL,
   EMAIL VARCHAR2(100) NOT NULL,
   PHONE VARCHAR2(40) NOT NULL,
   SIMPLE VARCHAR2(400) NOT NULL,
   ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL,
   MODIFY_DATE DATE DEFAULT SYSDATE,
   START_DATE DATE NOT NULL,
   END_DATE DATE NOT NULL,
   START_ENTER DATE NOT NULL,
   END_ENTER DATE NOT NULL,
   ACHIEVE_NY VARCHAR2(40) DEFAULT 'N' NOT NULL CHECK(ACHIEVE_NY IN('N', 'Y')),
   CONTENT VARCHAR2(4000) NOT NULL,
   ADDRESS VARCHAR2(4000),
   ADDRESS_DETAIL VARCHAR2(4000),
    DISPLAY_NY VARCHAR2(100) NOT NULL,
    EVENT_PASSWORD VARCHAR2(4000),
   HASH_TAG VARCHAR2(4000),
   DEL_NY VARCHAR2(10) DEFAULT 'N' NOT NULL CHECK(DEL_NY IN('N', 'Y')),   
   REP_NY VARCHAR2(10) DEFAULT 'N' NOT NULL CHECK(REP_NY IN('N', 'Y')),
   URL VARCHAR2(4000),
   MAX NUMBER NOT NULL,
   MAX_ACCESS VARCHAR2(10) NOT NULL,
   ADULT_ACCESS VARCHAR2(10) NOT NULL,
   CATEGORY_NO NUMBER NOT NULL,
   MEM_NO NUMBER NOT NULL,
   TABLE_NO NUMBER DEFAULT 2 NOT NULL REFERENCES TABLE_NAME,
    ATTEND_PASSWORD VARCHAR2(4000),
   COUNT NUMBER DEFAULT '0' NOT NULL,
   STATUS VARCHAR2(10) DEFAULT 'Y' NOT NULL   
);

-- 오프라인목표디데이 컬럼명
COMMENT ON COLUMN OFFLINE_CHALLENGE_D_DAY.NO IS '모임번호';
COMMENT ON COLUMN OFFLINE_CHALLENGE_D_DAY.TITLE IS '모임명';
COMMENT ON COLUMN OFFLINE_CHALLENGE_D_DAY.ID IS '개설자';
COMMENT ON COLUMN OFFLINE_CHALLENGE_D_DAY.NAME IS '담당자명';
COMMENT ON COLUMN OFFLINE_CHALLENGE_D_DAY.EMAIL IS '이메일';
COMMENT ON COLUMN OFFLINE_CHALLENGE_D_DAY.PHONE IS '전화번호';
COMMENT ON COLUMN OFFLINE_CHALLENGE_D_DAY.SIMPLE IS '간단소개';
COMMENT ON COLUMN OFFLINE_CHALLENGE_D_DAY.ENROLL_DATE IS '등록일자';
COMMENT ON COLUMN OFFLINE_CHALLENGE_D_DAY.MODIFY_DATE IS '수정일자';
COMMENT ON COLUMN OFFLINE_CHALLENGE_D_DAY.START_DATE IS '모임시작일자';
COMMENT ON COLUMN OFFLINE_CHALLENGE_D_DAY.END_DATE IS '모임종료일자';
COMMENT ON COLUMN OFFLINE_CHALLENGE_D_DAY.START_ENTER IS '접수시작일자';
COMMENT ON COLUMN OFFLINE_CHALLENGE_D_DAY.END_ENTER IS '접수종료일자';
COMMENT ON COLUMN OFFLINE_CHALLENGE_D_DAY.ACHIEVE_NY IS '달성여부';
COMMENT ON COLUMN OFFLINE_CHALLENGE_D_DAY.CONTENT IS '상세내용';
COMMENT ON COLUMN OFFLINE_CHALLENGE_D_DAY.ADDRESS IS '주소';
COMMENT ON COLUMN OFFLINE_CHALLENGE_D_DAY.ADDRESS_DETAIL IS '상세주소';
COMMENT ON COLUMN OFFLINE_CHALLENGE_D_DAY.DISPLAY_NY IS '노출여부';
COMMENT ON COLUMN OFFLINE_CHALLENGE_D_DAY.EVENT_PASSWORD IS '비밀번호';
COMMENT ON COLUMN OFFLINE_CHALLENGE_D_DAY.HASH_TAG IS '해시태그';
COMMENT ON COLUMN OFFLINE_CHALLENGE_D_DAY.DEL_NY IS '삭제여부';
COMMENT ON COLUMN OFFLINE_CHALLENGE_D_DAY.REP_NY IS '신고여부';
COMMENT ON COLUMN OFFLINE_CHALLENGE_D_DAY.URL IS 'url';
COMMENT ON COLUMN OFFLINE_CHALLENGE_D_DAY.MAX IS '정원';
COMMENT ON COLUMN OFFLINE_CHALLENGE_D_DAY.MAX_ACCESS IS '정원초과허용여부';
COMMENT ON COLUMN OFFLINE_CHALLENGE_D_DAY.ADULT_ACCESS IS '청소년접근제한여부';
COMMENT ON COLUMN OFFLINE_CHALLENGE_D_DAY.CATEGORY_NO IS '카테고리';
COMMENT ON COLUMN OFFLINE_CHALLENGE_D_DAY.MEM_NO IS '회원번호';
COMMENT ON COLUMN OFFLINE_CHALLENGE_D_DAY.TABLE_NO IS '테이블번호';
COMMENT ON COLUMN OFFLINE_CHALLENGE_D_DAY.ATTEND_PASSWORD IS '출석확인용비밀번호';
COMMENT ON COLUMN OFFLINE_CHALLENGE_D_DAY.COUNT IS '조회수';
COMMENT ON COLUMN OFFLINE_CHALLENGE_D_DAY.STATUS IS '상태';

-- ----------- OFFLINE_CHALLENGE_REGULAR -------------

-- 그룹번호 부여하기 위한 시퀀스 생성(오프라인목표정기)
CREATE SEQUENCE SEQ_OFF_CHALLENGE_REG_NO
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

-- 오프라인목표정기 테이블 생성
CREATE TABLE OFFLINE_CHALLENGE_REGULAR(
   NO NUMBER CONSTRAINT OFF_CHALLENGE_REG_NO_PK PRIMARY KEY,
   TITLE VARCHAR2(100) NOT NULL,
   ID VARCHAR2(100) NOT NULL,
   NAME VARCHAR2(100) NOT NULL,
   EMAIL VARCHAR2(100) NOT NULL,
   PHONE VARCHAR2(40) NOT NULL,
   SIMPLE VARCHAR2(400) NOT NULL,
   ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL,
   MODIFY_DATE DATE DEFAULT SYSDATE,
   START_DATE DATE NOT NULL,
   END_DATE DATE NOT NULL,
   START_ENTER DATE NOT NULL,
   END_ENTER DATE NOT NULL,
   ACHIEVE_NY VARCHAR2(40) DEFAULT 'N' NOT NULL CHECK(ACHIEVE_NY IN('N', 'Y')),
   CONTENT VARCHAR2(4000) NOT NULL,
   ADDRESS VARCHAR2(4000),
   ADDRESS_DETAIL VARCHAR2(4000),
    DISPLAY_NY VARCHAR2(100) NOT NULL,
    EVENT_PASSWORD VARCHAR2(4000),
   HASH_TAG VARCHAR2(4000),
   DEL_NY VARCHAR2(10) DEFAULT 'N' NOT NULL CHECK(DEL_NY IN('N', 'Y')),   
   REP_NY VARCHAR2(10) DEFAULT 'N' NOT NULL CHECK(REP_NY IN('N', 'Y')),
   URL VARCHAR2(4000),
   MAX NUMBER NOT NULL,
   MAX_ACCESS VARCHAR2(10) NOT NULL,
   ADULT_ACCESS VARCHAR2(10) NOT NULL,
   CATEGORY_NO NUMBER NOT NULL,
   MEM_NO NUMBER NOT NULL,
   TABLE_NO NUMBER DEFAULT 2 NOT NULL REFERENCES TABLE_NAME,
    ATTEND_PASSWORD VARCHAR2(4000),
   COUNT NUMBER DEFAULT '0' NOT NULL,
   STATUS VARCHAR2(10) DEFAULT 'Y' NOT NULL   
);

-- 오프라인목표정기 컬럼명
COMMENT ON COLUMN OFFLINE_CHALLENGE_REGULAR.NO IS '모임번호';
COMMENT ON COLUMN OFFLINE_CHALLENGE_REGULAR.TITLE IS '모임명';
COMMENT ON COLUMN OFFLINE_CHALLENGE_REGULAR.ID IS '개설자';
COMMENT ON COLUMN OFFLINE_CHALLENGE_REGULAR.NAME IS '담당자명';
COMMENT ON COLUMN OFFLINE_CHALLENGE_REGULAR.EMAIL IS '이메일';
COMMENT ON COLUMN OFFLINE_CHALLENGE_REGULAR.PHONE IS '전화번호';
COMMENT ON COLUMN OFFLINE_CHALLENGE_REGULAR.SIMPLE IS '간단소개';
COMMENT ON COLUMN OFFLINE_CHALLENGE_REGULAR.ENROLL_DATE IS '등록일자';
COMMENT ON COLUMN OFFLINE_CHALLENGE_REGULAR.MODIFY_DATE IS '수정일자';
COMMENT ON COLUMN OFFLINE_CHALLENGE_REGULAR.START_DATE IS '모임시작일자';
COMMENT ON COLUMN OFFLINE_CHALLENGE_REGULAR.END_DATE IS '모임종료일자';
COMMENT ON COLUMN OFFLINE_CHALLENGE_REGULAR.START_ENTER IS '접수시작일자';
COMMENT ON COLUMN OFFLINE_CHALLENGE_REGULAR.END_ENTER IS '접수종료일자';
COMMENT ON COLUMN OFFLINE_CHALLENGE_REGULAR.ACHIEVE_NY IS '달성여부';
COMMENT ON COLUMN OFFLINE_CHALLENGE_REGULAR.CONTENT IS '상세내용';
COMMENT ON COLUMN OFFLINE_CHALLENGE_REGULAR.ADDRESS IS '주소';
COMMENT ON COLUMN OFFLINE_CHALLENGE_REGULAR.ADDRESS_DETAIL IS '상세주소';
COMMENT ON COLUMN OFFLINE_CHALLENGE_REGULAR.DISPLAY_NY IS '노출여부';
COMMENT ON COLUMN OFFLINE_CHALLENGE_REGULAR.EVENT_PASSWORD IS '비밀번호';
COMMENT ON COLUMN OFFLINE_CHALLENGE_REGULAR.HASH_TAG IS '해시태그';
COMMENT ON COLUMN OFFLINE_CHALLENGE_REGULAR.DEL_NY IS '삭제여부';
COMMENT ON COLUMN OFFLINE_CHALLENGE_REGULAR.REP_NY IS '신고여부';
COMMENT ON COLUMN OFFLINE_CHALLENGE_REGULAR.URL IS 'url';
COMMENT ON COLUMN OFFLINE_CHALLENGE_REGULAR.MAX IS '정원';
COMMENT ON COLUMN OFFLINE_CHALLENGE_REGULAR.MAX_ACCESS IS '정원초과허용여부';
COMMENT ON COLUMN OFFLINE_CHALLENGE_REGULAR.ADULT_ACCESS IS '청소년접근제한여부';
COMMENT ON COLUMN OFFLINE_CHALLENGE_REGULAR.CATEGORY_NO IS '카테고리';
COMMENT ON COLUMN OFFLINE_CHALLENGE_REGULAR.MEM_NO IS '회원번호';
COMMENT ON COLUMN OFFLINE_CHALLENGE_REGULAR.TABLE_NO IS '테이블번호';
COMMENT ON COLUMN OFFLINE_CHALLENGE_REGULAR.ATTEND_PASSWORD IS '출석확인용비밀번호';
COMMENT ON COLUMN OFFLINE_CHALLENGE_REGULAR.COUNT IS '조회수';
COMMENT ON COLUMN OFFLINE_CHALLENGE_REGULAR.STATUS IS '상태';


-- -------------------- NOTICE -----------------------

-- 공지글 번호 부여하기 위한 시퀀스 생성
CREATE SEQUENCE SEQ_NTC
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

-- 공지사항 테이블 생성
CREATE TABLE NOTICE(
    NTC_NO NUMBER NOT NULL,
    NTC_WRITER VARCHAR(20) NOT NULL,
    NTC_TITLE VARCHAR(100) NOT NULL,
    NTC_CONTENT VARCHAR(2000) NOT NULL,
    NTC_CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    NTC_UPDATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    NTC_COUNT NUMBER DEFAULT 0 NOT NULL,
    NTC_DEL_NY VARCHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT NTC_DEL_NY_CK CHECK(NTC_DEL_NY IN('Y','N'))
);

-- 공지사항 컬럼명
COMMENT ON COLUMN NOTICE.NTC_NO IS '공지번호';
COMMENT ON COLUMN NOTICE.NTC_WRITER IS '작성자';
COMMENT ON COLUMN NOTICE.NTC_TITLE IS '공지제목';
COMMENT ON COLUMN NOTICE.NTC_CONTENT IS '공지내용';
COMMENT ON COLUMN NOTICE.NTC_CREATE_DATE IS '공지등록일';
COMMENT ON COLUMN NOTICE.NTC_UPDATE_DATE IS '공지수정일';
COMMENT ON COLUMN NOTICE.NTC_COUNT IS '조회수';
COMMENT ON COLUMN NOTICE.NTC_DEL_NY IS '삭제여부';

-- --------------------- BOARD -----------------------

-- 자유게시판 글 번호 부여하기 위한 시퀀스 생성
CREATE SEQUENCE SEQ_BOARD
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

-- 자유게시판 테이블 생성
CREATE TABLE BOARD(
    BOARD_NO NUMBER NOT NULL,
    BOARD_TITLE VARCHAR(50) NOT NULL,
    BOARD_CONTENT CLOB NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    MODIFY_DATE DATE DEFAULT SYSDATE NOT NULL,
    COUNT NUMBER DEFAULT 0 NOT NULL,
    REP_NY VARCHAR(60) DEFAULT 'N' NOT NULL CONSTRAINT BOARD_REP_NY_CK CHECK(REP_NY IN('Y','N')),
    DEL_NY VARCHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT BOARD_DEL_NY_CK CHECK(DEL_NY IN('Y','N')),
    CATEGORY NUMBER NOT NULL REFERENCES CATEGORY,
    MEM_NO NUMBER NOT NULL REFERENCES MEMBER,
    TABLE_NO NUMBER DEFAULT 10 NOT NULL REFERENCES TABLE_NAME
);

-- 자유게시판 컬럼명
COMMENT ON COLUMN BOARD.BOARD_NO IS '게시글번호';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '게시글제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '게시글내용';
COMMENT ON COLUMN BOARD.CREATE_DATE IS '게시글작성일';
COMMENT ON COLUMN BOARD.MODIFY_DATE IS '게시글수정일';
COMMENT ON COLUMN BOARD.COUNT IS '조회수';
COMMENT ON COLUMN BOARD.REP_NY IS '신고여부';
COMMENT ON COLUMN BOARD.DEL_NY IS '삭제여부';
COMMENT ON COLUMN BOARD.CATEGORY IS '카테고리';
COMMENT ON COLUMN BOARD.MEM_NO IS '회원번호';
COMMENT ON COLUMN BOARD.TABLE_NO IS '테이블번호';

-- 자유게시판 임시 데이터 입력
-- INSERT INTO BOARD(BOARD_NO, BOARD_TITLE, BOARD_CONTENT, CREATE_DATE, MODIFY_DATE, COUNT, REP_NY, DEL_NY, CATEGORY, MEM_NO, TABLE_NO) VALUES(SEQ_BOARD.NEXTVAL, '코딩팸 모집1', '서울 강남구 근처 코딩할 사람 모집급구', SYSDATE, SYSDATE, DEFAULT, 'N', 'N', 1, 6, 10);
-- INSERT INTO BOARD(BOARD_NO, BOARD_TITLE, BOARD_CONTENT, CREATE_DATE, MODIFY_DATE, COUNT, REP_NY, DEL_NY, CATEGORY, MEM_NO, TABLE_NO) VALUES(SEQ_BOARD.NEXTVAL, '코딩팸 모집2', '강원 속초시 근처 코딩할 사람 모집급구', SYSDATE, SYSDATE, DEFAULT, 'N', 'N', 1, 6, 10);
-- INSERT INTO BOARD(BOARD_NO, BOARD_TITLE, BOARD_CONTENT, CREATE_DATE, MODIFY_DATE, COUNT, REP_NY, DEL_NY, CATEGORY, MEM_NO, TABLE_NO) VALUES(SEQ_BOARD.NEXTVAL, '코딩팸 모집3', '영남고속도로 근처 코딩할 사람 모집급구', SYSDATE, SYSDATE, DEFAULT, 'N', 'N', 3, 6, 10);
-- INSERT INTO BOARD(BOARD_NO, BOARD_TITLE, BOARD_CONTENT, CREATE_DATE, MODIFY_DATE, COUNT, REP_NY, DEL_NY, CATEGORY, MEM_NO, TABLE_NO) VALUES(SEQ_BOARD.NEXTVAL, '코딩팸 모집4', '미쿡 뉴욕 근처 코딩할 사람 모집급구', SYSDATE, SYSDATE, DEFAULT, 'N', 'N', 5, 6, 10);
-- INSERT INTO BOARD(BOARD_NO, BOARD_TITLE, BOARD_CONTENT, CREATE_DATE, MODIFY_DATE, COUNT, REP_NY, DEL_NY, CATEGORY, MEM_NO, TABLE_NO) VALUES(SEQ_BOARD.NEXTVAL, '코딩팸 모집5', '도봉산역 근처 코딩할 사람 모집급구', SYSDATE, SYSDATE, DEFAULT, 'N', 'N', 4, 6, 10);

-- ------------------ ENTRY_LIST ---------------------

-- 참가자목록 테이블 생성
CREATE TABLE ENTRY_LIST(
    GROUP_NO NUMBER NOT NULL,
    GROUP_TITLE VARCHAR2(4000) NOT NULL,
    ENTRY_ID VARCHAR2(100) NOT NULL,
    WAIT_NY VARCHAR2(100) DEFAULT 'N' CHECK(WAIT_NY IN('Y','N')) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    MEM_NO NUMBER NOT NULL REFERENCES MEMBER,
    TABLE_NO NUMBER DEFAULT 13 NOT NULL REFERENCES TABLE_NAME
);

-- 참가자목록 컬럼명
COMMENT ON COLUMN ENTRY_LIST.GROUP_NO IS '모임번호';
COMMENT ON COLUMN ENTRY_LIST.GROUP_TITLE IS '모임이름';
COMMENT ON COLUMN ENTRY_LIST.ENTRY_ID IS '참가자아이디';
COMMENT ON COLUMN ENTRY_LIST.WAIT_NY IS '대기여부';
COMMENT ON COLUMN ENTRY_LIST.START_DATE IS '참가시작날짜';
COMMENT ON COLUMN ENTRY_LIST.END_DATE IS '참가종료날짜';
COMMENT ON COLUMN ENTRY_LIST.MEM_NO IS '회원번호';
COMMENT ON COLUMN ENTRY_LIST.TABLE_NO IS '테이블번호';

-- --------------------- REPLY -----------------------

-- 댓글 테이블 생성
CREATE TABLE REPLY(
    REPLY_NO NUMBER PRIMARY KEY,
    REPLY_CONTENT VARCHAR2(3000) NOT NULL,
    ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL,
    MODIFY_DATE DATE DEFAULT SYSDATE,
    DEL_NY VARCHAR2(60) DEFAULT 'N' CHECK(DEL_NY IN('Y','N')) NOT NULL,
    REP_NY VARCHAR2(60) DEFAULT 'N' CHECK(REP_NY IN('Y','N')) NOT NULL,
    RECOMMENT_NY VARCHAR2(60) DEFAULT 'N' CHECK(RECOMMENT_NY IN('Y','N')) NOT NULL,
    REPER_NO NUMBER NOT NULL,
    GROUP_BOARD_NO NUMBER NOT NULL,
    MEM_NO NUMBER NOT NULL REFERENCES MEMBER,
    TABLE_NO NUMBER NOT NULL REFERENCES TABLE_NAME
);

-- 댓글 컬럼명
COMMENT ON COLUMN REPLY.REPLY_NO IS '댓글번호';
COMMENT ON COLUMN REPLY.REPLY_CONTENT IS '댓글내용';
COMMENT ON COLUMN REPLY.ENROLL_DATE IS '작성일';
COMMENT ON COLUMN REPLY.MODIFY_DATE IS '수정일자';
COMMENT ON COLUMN REPLY.DEL_NY IS '삭제여부';
COMMENT ON COLUMN REPLY.REP_NY IS '신고여부';
COMMENT ON COLUMN REPLY.RECOMMENT_NY IS '대댓글여부';
COMMENT ON COLUMN REPLY.REPER_NO IS '참조댓글';
COMMENT ON COLUMN REPLY.GROUP_BOARD_NO IS '참조게시글번호';
COMMENT ON COLUMN REPLY.MEM_NO IS '회원번호';
COMMENT ON COLUMN REPLY.TABLE_NO IS '참조테이블번호';

-- ----------------- GROUP_MESSAGE -------------------

-- 실시간채팅(그룹채팅) 테이블 생성
CREATE TABLE GROUP_MESSAGE(
    CHANNEL_NO NUMBER PRIMARY KEY,
    MESSAGE_CONTENT VARCHAR2(4000) NOT NULL,
    CREATE_AT DATE DEFAULT SYSDATE NOT NULL,
    CHANNEL_ID VARCHAR2(1000) NOT NULL,
    MEM_NO NUMBER NOT NULL REFERENCES MEMBER
);

-- 실시간채팅 컬럼명
COMMENT ON COLUMN GROUP_MESSAGE.CHANNEL_NO IS '채널번호';
COMMENT ON COLUMN GROUP_MESSAGE.MESSAGE_CONTENT IS '내용';
COMMENT ON COLUMN GROUP_MESSAGE.CREATE_AT IS '메시지생성시간';
COMMENT ON COLUMN GROUP_MESSAGE.CHANNEL_ID IS '채널명';
COMMENT ON COLUMN GROUP_MESSAGE.MEM_NO IS '회원번호';

-- -------------------- UPLOAD -----------------------

-- 업로드번호 부여하기 위한 시퀀스 생성
CREATE SEQUENCE SEQ_UPLOAD
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

-- 업로드 테이블 생성
CREATE TABLE UPLOAD(
    UPLOAD_NO NUMBER NOT NULL,
    ORIGIN_NAME VARCHAR2(1000) NOT NULL,
    MODIFY_NAME VARCHAR2(1000) NOT NULL,
    GROUP_BOARD_NO NUMBER NOT NULL,
    TABLE_NO NUMBER DEFAULT 16 NOT NULL REFERENCES TABLE_NAME
);

-- 업로드 컬럼명
COMMENT ON COLUMN UPLOAD.UPLOAD_NO IS '업로드번호';
COMMENT ON COLUMN UPLOAD.ORIGIN_NAME IS '원본파일명';
COMMENT ON COLUMN UPLOAD.MODIFY_NAME IS '수정파일명';
COMMENT ON COLUMN UPLOAD.GROUP_BOARD_NO IS '참조게시글번호';
COMMENT ON COLUMN UPLOAD.TABLE_NO IS '테이블번호';

-- -------------------- GROUP_UPLOAD -----------------------

-- 업로드번호 부여하기 위한 시퀀스 생성
CREATE SEQUENCE SEQ_UPLOAD_NO
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

-- 업로드 테이블 생성
CREATE TABLE GROUP_UPLOAD(
    UPLOAD_NO NUMBER NOT NULL,
    ORIGIN_NAME VARCHAR2(1000),
    CHANGE_NAME VARCHAR2(1000),
    GROUP_BOARD_NO NUMBER NOT NULL,
    FILE_LEVEL NUMBER,
    FILE_PATH VARCHAR2(4000),
    TABLE_NO NUMBER
);

-- 업로드 컬럼명
COMMENT ON COLUMN GROUP_UPLOAD.UPLOAD_NO IS '업로드번호';
COMMENT ON COLUMN GROUP_UPLOAD.ORIGIN_NAME IS '원본파일명';
COMMENT ON COLUMN GROUP_UPLOAD.CHANGE_NAME IS '수정파일명';
COMMENT ON COLUMN GROUP_UPLOAD.GROUP_BOARD_NO IS '참조게시글번호';
COMMENT ON COLUMN GROUP_UPLOAD.FILE_LEVEL IS '파일레벨';
COMMENT ON COLUMN GROUP_UPLOAD.FILE_PATH IS '파일경로';
COMMENT ON COLUMN GROUP_UPLOAD.TABLE_NO IS '테이블번호';

-- -------------------- REPORT -----------------------

-- 신고번호 부여하기 위한 시퀀스 생성
CREATE SEQUENCE SEQ_REPORT
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

-- 신고 테이블 생성
CREATE TABLE REPORT(
    REP_NO NUMBER PRIMARY KEY,
    GROUP_BOARD_NO NUMBER NOT NULL,
    TABLE_NO NUMBER DEFAULT 14 NOT NULL REFERENCES TABLE_NAME
);

-- 신고 테이블 컬럼명
COMMENT ON COLUMN REPORT.REP_NO IS '신고번호';
COMMENT ON COLUMN REPORT.GROUP_BOARD_NO IS '참조게시글번호';
COMMENT ON COLUMN REPORT.TABLE_NO IS '테이블번호';

-- --------------------- ALERT -----------------------

-- 알림번호 부여하기 위한 시퀀스 생성
CREATE SEQUENCE SEQ_ALERT
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

-- 알림 테이블 생성
CREATE TABLE ALERT(
    ID_NO NUMBER PRIMARY KEY,
    GROUP_NO NUMBER,
    TABLE_NO NUMBER DEFAULT 15 NOT NULL REFERENCES TABLE_NAME,
    MEM_NO NUMBER NOT NULL REFERENCES MEMBER(MEM_NO),
    ALERT_CONTENT VARCHAR2(3000) NOT NULL,
    ALERT_DATE DATE DEFAULT SYSDATE NOT NULL,
    ALERT_TYPE NUMBER CONSTRAINT ALERT_TYPE_CK CHECK(ALERT_TYPE IN('1','2','3','4','5','6')),
    ALERT_READ_NY CHAR(10) DEFAULT 'N' CONSTRAINT ALERT_READ_NY_CK CHECK(ALERT_READ_NY IN('Y','N'))
);

-- 알림 컬럼명
COMMENT ON COLUMN ALERT.ID_NO IS '알림번호';
COMMENT ON COLUMN ALERT.TABLE_NO IS '모임번호';
COMMENT ON COLUMN ALERT.TABLE_NO IS '테이블번호';
COMMENT ON COLUMN ALERT.MEM_NO IS '회원번호';
COMMENT ON COLUMN ALERT.ALERT_CONTENT IS '알림내용';
COMMENT ON COLUMN ALERT.ALERT_DATE IS '알림일시';
COMMENT ON COLUMN ALERT.ALERT_TYPE IS '알림타입';
COMMENT ON COLUMN ALERT.ALERT_READ_NY IS '알림상태';

-- ------------------ LINK -------------------------

-- 링크번호 부여하기 위한 시퀀스 생성
CREATE SEQUENCE SEQ_LNO
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;
    
-- 링크 테이블 생성
CREATE TABLE LINK(
    LINK_NO NUMBER PRIMARY KEY,
    LINK_URL VARCHAR2(4000) NOT NULL
);

-- 링크 컬럼명
COMMENT ON COLUMN LINK.LINK_NO IS '링크번호';
COMMENT ON COLUMN LINK.LINK_URL IS '링크주소';

INSERT INTO LINK (LINK_NO, LINK_URL) VALUES (SEQ_LNO.NEXTVAL, 'https://meet.google.com/ujk-aqcq-ykr');
INSERT INTO LINK (LINK_NO, LINK_URL) VALUES (SEQ_LNO.NEXTVAL, 'https://meet.google.com/pce-qvcy-fmi');
INSERT INTO LINK (LINK_NO, LINK_URL) VALUES (SEQ_LNO.NEXTVAL, 'https://meet.google.com/hpz-zavr-hzd');
INSERT INTO LINK (LINK_NO, LINK_URL) VALUES (SEQ_LNO.NEXTVAL, 'https://meet.google.com/mpe-cpzv-ayz');
INSERT INTO LINK (LINK_NO, LINK_URL) VALUES (SEQ_LNO.NEXTVAL, 'https://meet.google.com/znh-pthg-guz');
INSERT INTO LINK (LINK_NO, LINK_URL) VALUES (SEQ_LNO.NEXTVAL, 'https://meet.google.com/gtz-ckgb-but');
INSERT INTO LINK (LINK_NO, LINK_URL) VALUES (SEQ_LNO.NEXTVAL, 'https://meet.google.com/bhj-soct-fgk');
INSERT INTO LINK (LINK_NO, LINK_URL) VALUES (SEQ_LNO.NEXTVAL, 'https://meet.google.com/wwh-ejbj-gxf');
INSERT INTO LINK (LINK_NO, LINK_URL) VALUES (SEQ_LNO.NEXTVAL, 'https://meet.google.com/wuq-beyp-gfe');
INSERT INTO LINK (LINK_NO, LINK_URL) VALUES (SEQ_LNO.NEXTVAL, 'https://meet.google.com/sza-xwzv-dzm');
INSERT INTO LINK (LINK_NO, LINK_URL) VALUES (SEQ_LNO.NEXTVAL, 'https://meet.google.com/qdm-zrpk-hmz');
INSERT INTO LINK (LINK_NO, LINK_URL) VALUES (SEQ_LNO.NEXTVAL, 'https://meet.google.com/zuv-cvev-zhm');

--------------------- commit -----------------------
COMMIT;